# Generated by Django 5.0.7 on 2024-07-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
